configVersion: '1.0.0'

settings:
  debug: false
  update-checker: true
  bstats: true
  mysql:
    use: false
    table-prefix: homes
    host: localhost
    port: 3306
    database: database
    username: root
    password: password
  homes:
    per-world: false
    need-permission: true
    max-amount: 28
    rename-permission: false
    sound-permission: false
    per-sound-permission: false
    teleport:
      unsafe: false
      cooldown:
        enabled: true
        cancel-on-move: true
        time: 5
      cost:
        enabled: false
        type: XP # Options: VAULT, XP, LEVEL, ITEM
        item: DIAMOND
        amount: 10
